### ISSUE TITLE
아이템 저장기능 필요

### ISSUE THREAD

**Issue by boradorish** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-11#116]
## 어떤 버그인가요?

> 인벤토리에서 아이템을 꺼내서 놓고, 다른 씬에 갔다 오면 아이템이 사라져 있음.
아이템 저장 기능 필요.

## 어떤 상황에서 발생한 버그인가요?

> 마을에서 꽃을 주운 뒤, 상점으로 가서 꽃을 내려 놓음. 
다른 씬에 갔다오면 내려놓은 꽃이 사라져 있음.

## 예상 결과

> 아이템이 내려놓은 자리에 있어야 함.

**Comment by PJH6029** [comment]
save & load 기능 dev에 머지된 상태인데, 여전히 똑같은가요?
