### ISSUE TITLE
씬 전환 시 유저 feature 제한

### ISSUE THREAD

**Issue by WannaRaiseaCat** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-11#63]
## 어떤 기능인가요?

씬 전환 진행시 캐릭터 view, movement, interaction 잠금
전환 후 잠금 해제 로직 구현 필요

## 작업 상세 내용

- [ ] TODO: view 잠금, 잠금해제 로직 구현
- [ ] TODO: movement 잠금, 잠금해제 로직 구현
- [ ] TODO: interaction 잠금, 잠금해제 로직 구현

**Comment by PJH6029** [comment]
해결. interaction은 별도 issue로 관리
