### ISSUE TITLE
마우스 사용 가능 상황에서 시야 회전 문제

### ISSUE THREAD

**Issue by Jukim2** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-11#92]
인벤토리를 키고 마우스를 막 돌리다가 인벤토리를 끄면 그 동안의 마우스 움직임이 시야 회전에 누적 적용이 되지않도록 해놓았었는데 그 기능이 사라짐.

**Comment by PJH6029** [comment]
어 이거 제가 없앤거 같습니다 ㅋㅋㅋ.. 드래그 버그 고치다가 InputHandler의 UpdateViewRot에서 `GameStateManager`의 view lock 여부를 확인하고있길래, 그 라인을 없앴는데 그거 원인인 듯 하네요 다시 수정하겠습니다
